### ISSUE TITLE
Consider supporting a random state function

### ISSUE THREAD

**Issue by justin-barca-at-camis** [ptrkcsk/license-plate-serial-generator#16]
Commonly utilities like this are used to generate fake test data. In this case, the user wants to see a varieties of states appear in the tests. Consider supporting an `any` function that randomly selects one of the states.

**Comment by justin-barca-at-camis** [comment]
Here's a PR for that: https://github.com/ptrkcsk/license-plate-serial-generator/pull/17

**Comment by ptrkcsk** [comment]
added `random()` in #17
